version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canvas-server
    image: canvas-server:latest
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CANVAS_SERVER_HOME: ${CANVAS_SERVER_HOME:-/opt/canvas-server/server}
      CANVAS_USER_HOME: ${CANVAS_USER_HOME:-/opt/canvas-server/users}
      CANVAS_ADMIN_EMAIL: ${CANVAS_ADMIN_EMAIL:-admin@canvas.local}
      CANVAS_ADMIN_PASSWORD: ${CANVAS_ADMIN_PASSWORD:-$(openssl rand -base64 16)}
    volumes:
      - ${CANVAS_SERVER_HOME:-./server}:/opt/canvas-server/server
      - ${CANVAS_USER_HOME:-./users}:/opt/canvas-server/users
