version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canvas-server
    image: canvas-server:latest
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      NODE_ENV: development
      CANVAS_SERVER_HOME: ${CANVAS_SERVER_HOME:-./server}
      CANVAS_USER_HOME: ${CANVAS_USER_HOME:-./user}
    volumes:
      - ${CANVAS_SERVER_HOME}:/opt/canvas-server/server
      - ${CANVAS_USER_HOME}:/opt/canvas-server/user
